GET http://localhost:3000/

### CREATE
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Category",
  "description": "Category Description"
}

### READ ALL
GET http://localhost:3000/categories

### READ
GET http://localhost:3000/categories/42

### UPDATE
PATCH http://localhost:3000/categories/42
Content-Type: application/json

{
  "name": "scifi",
  "description": "Ficção Científica"
}

### DELETE
DELETE http://localhost:3000/categories/44

###

GET http://localhost:3000/videos

### CREATE
POST http://localhost:3000/videos
Content-Type: application/json

{
  "title": "Video test",
  "description": "Video test description",
  "category_id": 8
}

### UPLOAD
POST http://localhost:3000/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="title"

Video test
------WebKitFormBoundary
Content-Disposition: form-data; name="description"

Video test description
------WebKitFormBoundary
Content-Disposition: form-data; name="category_id"

1
------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="video.mp4"
Content-Type: video/mp4

< ./video.mp4
------WebKitFormBoundary--

### DOWNLOAD
GET http://localhost:3000/videos/file/1711899400991_31546.mp4
