GET http://localhost:3000/

### CREATE
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Category",
  "description": "Category Description"
}

### READ ALL
GET http://localhost:3000/categories

### READ
GET http://localhost:3000/categories/42

### UPDATE
PATCH http://localhost:3000/categories/42
Content-Type: application/json

{
  "name": "scifi",
  "description": "Ficção Científica"
}

### DELETE
DELETE http://localhost:3000/categories/44

###

GET http://localhost:3000/videos

### CREATE
POST http://localhost:3000/videos
Content-Type: application/json

{
  "title": "Video test",
  "description": "Video test description",
  "category_id": 8
}
