version: '3'

services:
  mysql:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
      MYSQL_USER: fullcycle
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
